version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: hospital_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: hospital_backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/hospital_db

volumes:
  mongo_data:
